import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "../lib/registry";
import MobileNavigationShell from "@/components/MobileNavigationShell";

const mobileNavItems = [
  { key: "about", label: "О компании", href: "/about" },
  { key: "sites", label: "Площадки", href: "/locations" },
  {
    key: "products",
    label: "Продукция",
    children: [
      { key: "product-aggregates", label: "Щебень", href: "/products/aggregates" },
      { key: "product-sand", label: "Песок", href: "/products/sand" },
      { key: "product-mixtures", label: "Смеси", href: "/products/mixtures" },
    ],
  },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Вологодское карьерное управление",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          <MobileNavigationShell items={mobileNavItems} />
          <main className="app-main-hidden-on-mobile">{children}</main>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
